services:
  action:
    image: public.ecr.aws/infrastructure-blocks/list-template-repository-instances-action:latest
    build:
      context: ../
      dockerfile: docker/action/Dockerfile
    container_name: list-template-repository-instances-action
