name: Self Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: without-instances
        with:
          github-token: ${{ secrets.PAT }}
      - name: Show outputs
        run: |
          echo "instances=${{ steps.without-instances.outputs.instances }}"
          echo "instances-length=${{ steps.without-instances.outputs.instances-length }}"
      - uses: ./
        id: with-instances
        with:
          github-token: ${{ secrets.PAT }}
          template-repository: infrastructure-blocks/ts-lib-template
      - name: Show outputs
        run: |
          echo "instances=${{ steps.with-instances.outputs.instances }}"
          echo "instances-length=${{ steps.with-instances.outputs.instances-length }}"
